import type { Metadata } from "next";
import { Toaster } from "sonner";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/providers/theme-provider";
import { ConvexClientProvider } from "@/components/providers/convex-provider";
import { ModalProvider } from "@/components/providers/modal-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Suspense } from "react";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Motion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en suppressHydrationWarning">
      <body className={inter.className}>
        <Suspense>
          <ClerkProvider>
            <ConvexClientProvider>
              <EdgeStoreProvider>
                <ThemeProvider attribute="class" defaultTheme="system"
                  enableSystem disableTransitionOnChange
                  storageKey="motion-theme-2">
                  <Toaster position="bottom-center" />
                  <ModalProvider />
                  {children}
                </ThemeProvider>
              </EdgeStoreProvider>
            </ConvexClientProvider>
          </ClerkProvider>
        </Suspense>
      </body>
    </html>
  );
}
